DELETE http://localhost:3003/api/blogs/666fe3513020f170af3b7a3f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtjbGFya3NvbiIsImlkIjoiNjY2YzA0ZGIxNWRkODIyZDY1MjI4YzgzIiwiaWF0IjoxNzE4NjA1MzM2fQ.lx4J1hgRXp6GqcVvA1-JCqSQTNpOfO4Y6OuJIJHa0SU

###
DELETE http://localhost:3003/api/blogs/6666f1bd90956f165b3e2df1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtjbGFya3NvbiIsImlkIjoiNjY2YzA0ZGIxNWRkODIyZDY1MjI4YzgzIiwiaWF0IjoxNzE4NjA1MzM2fQ.lx4J1hgRXp6GqcVvA1-JCqSQTNpOfO4Y6OuJIJHa0SU